const Colecao_Dados_Meteoros = [
{nome:"Alfa Centaurídeos", data_inicio:"01/28",data_fim:"02/21",data_pico:"Fev/8",Ascencao_Recta:"210",Declinacao:"-59",Velocidade:"56",THZ:"6",intensidade:"Media"},
{nome:"Gama Normídeos", data_inicio:"02/25",data_fim:"03/22",data_pico:"Mar/14",Ascencao_Recta:"239",Declinacao:"-50",Velocidade:"56",THZ:"6",intensidade:"Media"},
{nome:"Líridas", data_inicio:"04/16",data_fim:"04/25",data_pico:"Abr/22",Ascencao_Recta:"271",Declinacao:"+34",Velocidade:"49",THZ:"18",intensidade:"Forte com meteoros rápidos e persistentes"},
{nome:"Pí Pupídeos", data_inicio:"04/15",data_fim:"04/28",data_pico:"Abr/23",Ascencao_Recta:"110",Declinacao:"-45",Velocidade:"18",THZ:"Variável",intensidade:"Irregular"},
{nome:"Eta Aquáridas",data_inicio:"04/19",data_fim:"05/28",data_pico:"Mai/5",Ascencao_Recta:"338",Declinacao:"-01",Velocidade:"66",THZ:"65",intensidade:"Forte com meteoros muito rápidos e de grande comprimento"},
{nome:"Eta Líridas",data_inicio:"05/03", data_fim:"05/14",data_pico:"Mai/8",Ascencao_Recta:"287",Declinacao:"+44",Velocidade:"43",THZ:"3",intensidade:"Fraca"},
{nome:"Bootídeos de Junho", data_inicio:"06/28", data_fim:"06/28",data_pico:"Jun/28",Ascencao_Recta:"224",Declinacao:"+48",Velocidade:"18",THZ:"Variável",intensidade:"Irregular"},
{nome:"Piscis Austrinídeos",data_inicio:"07/15",data_fim:"08/10",data_pico:"Jul/28",Ascencao_Recta:"341",Declinacao:"-30",Velocidade:"35",THZ:"5",intensidade:"Media"},
{nome:"Delta Aquáridas Do Sul", data_inicio:"07/12",data_fim:"08/19",data_pico:"Jul/28",Ascencao_Recta:"340",Declinacao:"-16",Velocidade:"41",THZ:"16",intensidade:"Forte com meteoros lentos e rasto comprido"},
{nome:"Alfa Capricornídeos", data_inicio:'07/03',data_fim:"08/15",data_pico:"Jul/30",Ascencao_Recta:"307",Declinacao:"-10",Velocidade:"23",THZ:"5",intensidade:"Fraco"},
{nome:"Perseidas",data_inicio:"08/17",data_fim:"08/24",data_pico:"Ago/12",Ascencao_Recta:"48",Declinacao:"+58",Velocidade:"59",THZ:"100",intensidade:"Forte e muito rápidas"},
{nome:"Capa Cignídeos", data_inicio:"08/03",data_fim:"08/25",data_pico:"Ago/17",Ascencao_Recta:"286",Declinacao:"+59",Velocidade:"25",THZ:"3",intensidade:"Fraca com velocidades médias e brilhantes"},
{nome:"Alfa Aurigídeos", data_inicio:"08/25",data_fim:"09/08",data_pico:"Set/1",Ascencao_Recta:"91",Declinacao:"+39",Velocidade:"66",THZ:"6",intensidade:"Média com meteoros muito rápidos e persistentes"},
{nome:"Perseidas de Setembro",data_inicio:"09/05",data_fim:"10/10",data_pico:"Set/8",Ascencao_Recta:"48",Declinacao:"+40",Velocidade:"64",THZ:"5",intensidade:"Média com meteoros rápidos e persistentes"},
{nome:"Dracónidas",data_inicio:"10/06",data_fim:"10/10",data_pico:"Out/8",Ascencao_Recta:"262",Declinacao:"+54",Velocidade:"20",THZ:"Variável",intensidade:"Irregular"},
{nome:"Táuridas",data_inicio:"09/10",data_fim:"11/20",data_pico:"Out/10",Ascencao_Recta:"32",Declinacao:"+9",Velocidade:"27",THZ:"5",intensidade:"Fraca"},
{nome:"Delta Aurigídeos",data_inicio:"09/22",data_fim:"10/23",data_pico:"Out/10",Ascencao_Recta:"84",Declinacao:"+44",Velocidade:"64",THZ:"2",intensidade:"Fraca"},
{nome:"Épsilon Geminídeos",data_inicio:"10/14",data_fim:"10/27",data_pico:"Out/18",Ascencao_Recta:"102",Declinacao:"+27",Velocidade:"70",THZ:"3",intensidade:"Fraca"},
{nome:"Oriónidas",data_inicio:"10/02",data_fim:"11/07",data_pico:"Out/21",Ascencao_Recta:"95",Declinacao:"+16",Velocidade:"66",THZ:"25",intensidade:"Forte com meteoros rápidos e persistentes"},
{nome:"Leo Minorídeos",data_inicio:"10/21",data_fim:"10/23",data_pico:"Out/22",Ascencao_Recta:"162",Declinacao:"+37",Velocidade:"62",THZ:"2", intensidade:"Fraca"},
{nome:"Táuridas do Norte",data_inicio:"11/01",data_fim:"11/25",data_pico:"Nov/12",Ascencao_Recta:"58",Declinacao:"+22",Velocidade:"29",THZ:"5",intensidade:"Média com meteoros muito lentos mas brilhantes"},
{nome:"Leónidas",data_inicio:"11/14",data_fim:"11/21",data_pico:"Nov/17",Ascencao_Recta:"152",Declinacao:"+22",Velocidade:"71",THZ:"Variável",intensidade:"Irregular com meteoros muito rápidos, atingindo um pico de 33 em 33 anos"},
{nome:"Alfa Monocerotídeos",data_inicio:"11/15",data_fim:"11/25",data_pico:"Nov/21",Ascencao_Recta:"117",Declinacao:"+01",Velocidade:"65",THZ:"Variável",intensidade:"Irregular"},
{nome:"Fenícidas",data_inicio:"11/28",data_fim:"12/09",data_pico:"Dez/6",Ascencao_Recta:"18",Declinacao:"-53",Velocidade:"18",THZ:"10",intensidade:"Irregular"},
{nome:"Quadrântidas", data_inicio:"12/28",data_fim:"01/12",Ascencao_Recta:"230",Declinacao:"+49",Velocidade:"41",THZ:"120",intensidade:"Forte com velocidades médias",data_pico:"Jan/4"},
{nome:"Pupidas Velidas",data_inicio:"12/02",data_fim:"12/16",data_pico:"Dez/12",Ascencao_Recta:"123",Declinacao:"-45",Velocidade:"40",THZ:"10",intensidade:"Media"},
{nome:"Monocerotídeos",data_inicio:"11/27",data_fim:"12/17",data_pico:"Dez/8",Ascencao_Recta:"100",Declinacao:"+08",Velocidade:"42",THZ:"2",intensidade:"Fraca"},
{nome:"Sigma Hidrídeos",data_inicio:"12/03", data_fim:"12/15",data_pico:"Dez/12",Ascencao_Recta:"127",Declinacao:"+02",Velocidade:"58",THZ:"3",intensidade:"Fraca"},
{nome:"Gemínidas",data_inicio:"12/07",data_fim:"12/17",data_pico:"Dez/14",Ascencao_Recta:"112",Declinacao:"+33",Velocidade:"35",THZ:"120",intensidade:"Forte com velocidades médias, meteoros brancos e numerosos"},
{nome:"Coma Berenicídeos",data_inicio:"12/12",data_fim:"01/23",data_pico:"Dez/20",Ascencao_Recta:"175",Declinacao:"+18",Velocidade:"65",THZ:"3",intensidade:"Fraca"},
{nome:"Leo Minorídeos de Dezembro",data_inicio:"12/05",data_fim:"02/04",data_pico:"Dez/19",Ascencao_Recta:"161",Declinacao:"+30",Velocidade:"64",THZ:"5",intensidade:"Media"},
{nome:"Úrsidas",data_inicio:"12/17",data_fim:"12/26",data_pico:"Dez/20",Ascencao_Recta:"217",Declinacao:"+76",Velocidade:"33",THZ:"10",intensidade:"Media"},
];
export default Colecao_Dados_Meteoros;

